# Server
server.port=8089

# Application
spring.application.name=gateway

# Routes
spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=items-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/items/**

spring.cloud.gateway.routes[2].id=categories-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/categories/**

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true

# Client ID del registro del API en Entra ID
spring.cloud.azure.active-directory.credential.client-id=482ff19e-3fc5-43ec-8a5e-31ec71c950d3
spring.cloud.azure.active-directory.profile.tenant-id=24597f44-c110-4081-a777-adae3102afac

# Application ID URI configurado en "Expose an API"
spring.cloud.azure.active-directory.app-id-uri=api://482ff19e-3fc5-43ec-8a5e-31ec71c950d3

# Fallback para auto-configuración de WebFlux (ReactiveJwtDecoder)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/24597f44-c110-4081-a777-adae3102afac/v2.0

# Actuator
management.endpoints.web.exposure.include=health,info,gateway

